apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: big-data-infrastructure
build:
  artifacts:
    - image: greifmch/client
      context: Express-React-web-app/client
      docker:
        dockerfile: Dockerfile
    - image: greifmch/pyspark
      context: Pyspark
      docker:
        dockerfile: Dockerfile
    - image: greifmch/server
      context: Express-React-web-app/server
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/*.yaml
