apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyspark-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyspark
  template:
    metadata:
      labels:
        app: pyspark
    spec:
      containers:
        - name: pyspark
          image: greifmch/pyspark